#!/usr/bin/env bash

serviceFile="frostServer.service"
serviceTargetDirectory="/etc/systemd/system/"

nginxFile="frostServer.nginx"
nginxTargetDirectory="/etc/nginx/sites-enabled/"

cat >$nginxFile <<EOF
server {
    listen 80;
    
    location / {
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://unix:$(pwd)/../frostServer.sock;
    }    
}
EOF

cat >$serviceFile <<EOF
[Unit]
Description=Gunicorn instance to serve frostServer
After=network.target

[Service]
User=alarm
Group=alarm
WorkingDirectory="$(pwd)/../"
ExecStart=gunicorn wsgi:application \\
         --bind unix:frostServer.sock \\
         --workers 1 \\
         --threads 10 \\
         --timeout 1800

[Install]
WantedBy=multi-user.target
EOF


ln -svf $(realpath $nginxFile) $nginxTargetDirectory
systemctl enable nginx
systemctl start nginx

ln -svf $(realpath $serviceFile) $serviceTargetDirectory
systemctl enable $serviceFile
systemctl start $serviceFile
