#+title: FrostAV Final Report
* Evaluation and Analysis
** Requirements Evaluation
*** Problem Domain Requirements
The main problem-domain requirements for this project are:
   1. Given a _lane_, the car must travel approximately parallel to it,
      such that the car stays within its _boundaries_ consistently,
      and, if the car is to accidentally leave it, it promptly
      returns.
   2. Given a _corner_, the car must turn, continuing from the car’s
      current _lane_ to the next, such that the car stays within its
      _boundaries_ consistently, and, if the car is to accidentally
      leave it, it promptly returns.
   3. Given an _obstacle_, the car must stop until it is moved
      further from the car, or it is removed from _circuit boundaries_.
   4. Given a _sign_, the car must respond to the event provided by it.
   5. Given a _circuit_, the car must complete a full loop.
The completed project is fully capable of meeting requirement 1, partially capable of 2 and 5 and unable to meet 3 and 4. The car can successfully navigate a straight path and recover from small excursions outside of the lane boundaries. The car will also safely come to a stop if it is too far outside of the lanes to recover. The car is also capable of navigating corners with some difficulty and can complete a circuit after a few tries. Obstacle detection and sign detection was never implemented due to a lack of time.

In addition to these problem-domain requirements, there were also component level specifications for the vehicle itself and its control system. The vehicle requirements are divided into two sections, the upper and lower chassis. For the control system and control modules, the following requirements apply.
*** Control System:
    The Control System shall:
   1. Interface with vehicle peripherals, such as, motors, servos,
      batteries, etc.
   2. Be the only system coupled to the vehicle. 
   3. Have a subset of Control Modules for each peripheral in need
      of control.

*** Control Modules:
    Each Control Module shall:
   1. Encapsulate a single purpose, such that, one controller controls
      a single peripheral.
   2. Couple to a peripheral electronically, not mechanically.
   3. Be able to communicate with other controllers via a wired bus.
   4. Be able to communicate with non-controllers that depend on it,
      via a wired bus.
   5. Communicate with other controllers and non-controllers via a
      single shared wired bus.

All the control system and control module requirements were met, except for the requirement that each control module must control a single peripheral. In the final design, the ATMEGA328 is used for both servo and throttle control. Otherwise, the control system was able to successfully interface with the vehicle peripherals using control modules, and the control modules share a single I2C bus. All control modules can communicate with the Raspberry Pi, which runs the main control system, and with each other (even though this capability was not utilized for the final design).
** Additional Capabilities
** Unique Innovations
** Problems
* Test Results
* Design Documentation (Appendix)
