* System Constraints
  The system should be capable of controlling the car without any
  sensors built into the car chassis itself (no encoders, speed sensors,
  etc.) The main navigation system should run on embedded Linux, and
  interface with the car using an AVR or similar microcontroller. The
  car use two cameras in a stereo configuration, along
  with an IMU (accelerometer and gyroscope) for navigating the course.

* Lower Chassis Constraints
  1. Must have the ability to store up to two 3-cell Litium Ion Battery.
  2. Must house the drive train and gearbox through the middle.
  3. Must contain all required components with little to no interference.
  4. Must be secrely fastened using M5 bolts to the rest of the lower chasis, as it is reponsible for holding the weight of the upper chassis and hardware.
  5. Batteries must be secured using velcro straps.
  6. Electronic Speed Controller (Motor Driver) may optionally be mounted in the lower chasis.

* Upper Chassis Constraints
  1. The second tier must mount the central processing unit, power supply unit, AVR chips, and both cameras.
  2. This layer must implement a quick disconnect mounting system.
  3. Must having a hole through the platform for wire managment and connections.
  
